import Head from 'next/head'
import SectionTestimonials from '../containers/Home/SectionTestimonials'
import SectionWhatIs from '../containers/Home/SectionWhatIs'
import HomeContainer from '../styles/styledHome'

export default function Home() {
  return (
    <HomeContainer>
      <Head>
        <title>Mentoria Lab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>Azul 1</section>
      <SectionWhatIs />
      <section id='howIt'>Azul 2</section>
      <SectionTestimonials />
    </HomeContainer>
  )
}
