import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mentoria Lab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Nosso primeiro projeto MENTORIA LAB
        </h1>

        <p className={styles.description}>
          Mentoria pra todo mundo! 😁 Meninas podem alterar tudo, fiquem a vontade pra fazer bagunça, estamos aqui para aprender!
        </p>

      </main>

      <footer className={styles.footer}>

        Com 🧡
          <span className={styles.logo}>
          <a href="https://github.com/React-Girls" target="_blank"
            rel="noopener noreferrer">React Girls </a>
        </span>

      </footer>
    </div >
  )
}
