import NextHeader from 'next/head'

export default function Header({ title }){

    return(
        <NextHeader>            
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            
            <title>
                {title}
            </title>
        </NextHeader>
    )
}